### ISSUE TITLE
ldist_loss  not defined in main code

### ISSUE THREAD

**Issue by shashankvkt** [jhayes14/UAN#1]
Thank you for providing this code.
Actually, ldist_loss  has not been defined in main.py. 
If it has been a mistake from my end, kindly forgive me for the same. Thanks

**Comment by jhayes14** [comment]
Thanks, should be fixed now

**Comment by shashankvkt** [comment]
Thank you. This is not an issue but a small query which I have.

I am using another dataset to generate the perturbation using your code just for study purpose. However, my L2 dist is of the order 10e-7 or 10e-8 after each epoch. Could you kindly advise as to are these values ideal or is there a method to bring it of the order 10e-3?
Thanks
